### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by GintsM**
Created, HTML, CSS .git/workflow with HTML/CSS  linters and git ignore

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @GintsM,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

- First the **linters.yml** should be inside the **.GitHub/workflows**.
- Second you should add linters **StyleLint & hintrc**.
- Third the gitignore should contains the **node_modules & test.ms not test**
- Four the **PR** should have summary about the the project.

jdjsj
pppp


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GintsM** [comment]
Hi 
Small question, seems everything is more or less solved, I hope the description, like I made, is also great, will take into account in the future, but when I see through files, I notice everything is green except, missing one line at the end of the files. Should I change those or that is great?
Thanks in advance

**Review by emmanuellekamwa — CHANGES_REQUESTED** [review]
**STATUS: CHANGES REQUESTED 🛑🛠**
Hello @GintsM 👋🏽
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
- Your branch has conflicting files that need to be resolved. Please fix that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GintsM** [comment]
Even don't have a slightly idea, what is going wrong, why Linters showing no pass.
Error: No files matching the pattern "**/*.{css,scss}" were found. - for Linters Stylelint
And
Error: No URLs provided to collect and no HTML files found in staticDistDir - for Lighthouse
Google couldn't help this time

**Review by ZeenatLawal — APPROVED** [review]
Hi @GintsM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
6vEo


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
